### ISSUE TITLE
Editing a reply message mentions the user youre replying to

### ISSUE THREAD

**Issue by schlopp** [Voxel-Fox-Ltd/VoxelBotUtils#118]

**Comment by 4Kaylum** [comment]
To clarify, Schlopp wants to change this behaviour (which is the default in D.py) to maintain the mention status of the original message.

**Comment by 4Kaylum** [comment]
For this I can take the original `allowed_mentions` and `mentions` attrs and combine them, if there's a message reference.

**Comment by 4Kaylum** [comment]
I did a bunch of testing on this and adding this just isn't intuitive, and not possible with `PartialMessage`.
