### ISSUE TITLE
`mention_author` parameter for `Message.edit`, simular to what `Message.send` has

### ISSUE THREAD

**Issue by schlopp** [Voxel-Fox-Ltd/VoxelBotUtils#119]

**Comment by 4Kaylum** [comment]
This can be achieved with allowed mentions for future Kae reference - https://discordpy.readthedocs.io/en/latest/api.html#discord.AllowedMentions.replied_user

**Comment by 4Kaylum** [comment]
This won't work in a way that's... good. I won't be able to edit `allowed_mentions` to be identical to the original message, as this isn't something that Discord greatly supports. If this is something that you want to add then I'd recommend setting `allowed_mentions` with your original message send.
