### ISSUE TITLE
IMPORTANT - owner only cog with `create_cog`

### ISSUE THREAD

**Issue by schlopp** [Voxel-Fox-Ltd/VoxelBotUtils#122]
Currently [`menus.Menu.create_cog`](https://voxelbotutils.readthedocs.io/en/latest/apireference.html?highlight=create_cog#voxelbotutils.menus.Menu.create_cog) doesn't support owner only cogs.
This creates some VERY bad bugs (I am not supposed to be able to use this):
![image](https://user-images.githubusercontent.com/67605203/128354238-338148bb-be0e-4cf5-9f38-7919d0020e8b.png)
I think a `owner_only: Optional[bool] = False` arg for [`menus.Menu.create_cog`](https://voxelbotutils.readthedocs.io/en/latest/apireference.html?highlight=create_cog#voxelbotutils.menus.Menu.create_cog) would be pretty hot

**Comment by schlopp** [comment]
`permissions: Optional[List[str]] = []` would be pretty hot
Example:
`x.create_cog(permissions=['manage_messages']` > cog can only be used by people with the `manage_messages` perm

**Comment by 4Kaylum** [comment]
Cool thank you that's just something I missed. I'd prefer it to be a manage guild permission if you want to PR it in, but if not then I'll do that later today. I'll grandfather it in to a 0.5.10 release so you don't need to wait for a 0.6 release, though you can create your own cog and command and use `settings_menu.start(ctx)` in it.

**Comment by 4Kaylum** [comment]
oh I didn't read the second message that would be very good
