### ISSUE TITLE
commands.Cog breaks default help command

### ISSUE THREAD

**Issue by rawr-x3** [Voxel-Fox-Ltd/VoxelBotUtils#13]
Kae was going to make this issue but I wanted to contribute. Anyway, screenshot is below.![image](https://user-images.githubusercontent.com/58949994/101231445-529e9780-3679-11eb-87d9-5783cebc0394.png)

**Comment by 4Kaylum** [comment]
I should be overriding `qualified_name` - https://github.com/Rapptz/discord.py/blob/master/discord/ext/commands/cog.py#L152-L154
