### ISSUE TITLE
Add a source command

### ISSUE THREAD

**Issue by iHeroGH** [Voxel-Fox-Ltd/VoxelBotUtils#18]
The command prints the code of whatever command it is the user wants to see. https://cdn.discordapp.com/attachments/764056789666365440/789033646400077854/unknown.png

**Comment by fadedmax** [comment]
Could this be achieved by stealing the jishaku source command?

**Comment by iHeroGH** [comment]
That's the plan :fingerguns:

**Comment by 4Kaylum** [comment]
Added in 12ce8cd319cce4567bf4605375a2e290329ba9c8.
