### ISSUE TITLE
Creating a website config should append requirements.txt with requirements for website

### ISSUE THREAD

**Issue by fadedmax** [Voxel-Fox-Ltd/VoxelBotUtils#28]
for people running the website for the first time, it doesnt add the website requirements, so i have to install them manually.

**Comment by 4Kaylum** [comment]
This will need me to do some fancy stuff in the main file, but it's definitely something that's preferable. I can't just delete and remake the file. Read and regex sub the line, maybe?

Needs more think.

**Comment by fadedmax** [comment]
Honestly i was thinking just to open the file, and start \n'in it, 

I didn't think this would need much thinking, store the requirements for the website in a list, append those requirements to the file.

Does need more think

**Comment by 4Kaylum** [comment]
Ah, I see. You just installed it wrong. If you `pip install voxelbotutils` then you get the bot requirements, if you `pip install voxelbotutils[web]` then you get the web requirements as well.

**Comment by fadedmax** [comment]
Fair, alot of the users of VBU update directly from git, it would be nice to append the actual project requirements.txt whenever you create the website config, get what i mean?

**Comment by 4Kaylum** [comment]
> alot of the users of VBU update directly from git

Just because I'm regularly updating. I think I'm *very soon* approaching a point where I can just leave it.

**Comment by 4Kaylum** [comment]
It shouldn't be up to the lib to update the requirements for a project.
