### ISSUE TITLE
Send notification to user when bot hits more than 2000 guilds per shard

### ISSUE THREAD

**Issue by 4Kaylum** [Voxel-Fox-Ltd/VoxelBotUtils#29]
Ofc we'll need to verify the accuracy of this with the intents but still

**Comment by 4Kaylum** [comment]
Decided against this because it's super easy to set up monitoring with DataDog.

**Comment by Silverdimond** [comment]
> Decided against this because it's super easy to set up monitoring with DataDog.

It still would be easy to implement and does not require a subscription like DataDog does.

**Comment by 4Kaylum** [comment]
> It still would be easy to implement and does not require a subscription like DataDog does.

It requires the guilds scope, at very least. 
Feel free to write and PR it yourself if you're interested, but I no longer am.
