### ISSUE TITLE
add "getprefix" command

### ISSUE THREAD

**Issue by SpicyTakis** [Voxel-Fox-Ltd/VoxelBotUtils#41]

**Comment by SpicyTakis** [comment]
This could also be implemented into the current prefix command. 
If the user doesnt supply a prefix to set it to, it displays the current prefix for that server. This would require checking the users permissions in the function, though.

**Comment by 4Kaylum** [comment]
> This would require checking the users permissions in the function, though.

That's fine - that's easy enough to do. I've learned that `.predicate` is a thing - `await commands.has_guild_permissions(manage_guild=True).predicate(ctx)` runs the check for you. It's pretty neat. You can probably implement this if you wanted to.

**Comment by 4Kaylum** [comment]
@Caity-chan ping so you are aware of what's happening.
