### ISSUE TITLE
Send payload to event webhook

### ISSUE THREAD

**Issue by fadedmax** [Voxel-Fox-Ltd/VoxelBotUtils#5]
It would be nice to have a
`utils.send_event('This is a example of a event log.`
style thing to help with special commands being ran eg, if something fails in a cog, you can send messages to the event webhook

**Comment by 4Kaylum** [comment]
How's something along the lines of `await bot.event_webhook.send(...)` with the normal `Channel.send` syntax?

**Comment by fadedmax** [comment]
Looks good, i think it also might be good to have a `await bot.alert.send("Oh no, something happened thats... actually kinda bad!") which can dm the owners, and go to the event webhook. Just a suggestion and a whole other issue in its self.
