### ISSUE TITLE
Add command to output help to the current channel, ignoring all permission checks

### ISSUE THREAD

**Issue by 4Kaylum** [Voxel-Fox-Ltd/VoxelBotUtils#67]

**Comment by fadedmax** [comment]
You didn't provide a description so here are my ways of going about this;
(for context. "dm" refers to direct messaging the user, "send" refers to sending it in the channel the command was ran)

1. Bot's can set a config flag to dm/send in the chat.

2. Server Admins can set a server setting to dm or to send.

Or you can do both of these in a way, Bot's have the ability to dm and send the help message(as per a config flag), but the server owner/admin can decide with a `setup` command part, whether to do it or not.

**Comment by 4Kaylum** [comment]
My plan for this was maybe a subcommand or alternative help command that set content to always output to a given channel - maybe checking if the given user has manage message permissions? Something like `!helpchannel` to output the help content to channel instead of DMs.

This isn't something I want to change on a per-server basis, I still want the main help command to go to DMs. I've just seen a lot of people ask for "how to send help to a channel instead of DMs", so I figured I'd try think something up.

**Comment by fadedmax** [comment]
I like that. I think maybe manage channels since manage messages is given to alot of helpers, of which now that is say that outloud that is a good idea. manage messages permission to run !helpchannel, i don't like the command name but i can't think of anything better so it will do :)

**Comment by 4Kaylum** [comment]
Closed with 19f5fb9f8aaca24e995d786ccb443f742f3eb158. Had to do some hacky stuff to get it working because apparently the help command doesn't have an `.update` method like every other command in D.py, but it's workin now.
