### ISSUE TITLE
Setting no presence, returns a error and locks the bot in a reconnecting state

### ISSUE THREAD

**Issue by fadedmax** [Voxel-Fox-Ltd/VoxelBotUtils#79]
![unknown.png](https://cdn.discordapp.com/attachments/785651028908572685/839952429479100462/unknown.png)

Idealy should be fixed, since having no set presence should be an option

**Comment by 4Kaylum** [comment]
Noting that I've found this only works for bots with an explicit shard count set - it'll work by without this on 0.3.1, but for now you can launch with `--shardcount 1 --min 0 --max 0`.
