### ISSUE TITLE
Have messages be an alternate to buttons

### ISSUE THREAD

**Issue by iHeroGH** [Voxel-Fox-Ltd/VoxelBotUtils#93]
I'm not too sure how the components stuff works with Voxel Bot Utils, but if it is possible, having it so users can type the text that is inside a button they want to choose in cases where the button click fails might be very helpful. 

Could have the wait_for check make sure the text they inputted is within the text in the buttons and then dispatch the interaction listener.

**Comment by 4Kaylum** [comment]
> having it so users can type the text that is inside a button

I'm not certain I understand. Could you give an example of the kind of thing you mean for this?

**Comment by iHeroGH** [comment]
p.shop 
Buttons with the text "Cactus" "Giraffe" "Holotree" "Cancel" etc. but the buttons don't work

user can type "cactus" "giraffe" etc to make their selection as if they pressed the button

**Comment by 4Kaylum** [comment]
You can do this with waiting for multiple events using asyncio:
```python
done, pending = asyncio.wait(
  [
    bot.wait_for("message"),
    bot.wait_for("component_interaction"),
  ],
  return_when=asyncio.FIRST_COMPLETED,
)
```
